apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31568     # Fix for your exposed port

