apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: LoadBalancer
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Changed to 80 to match the container port

