apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31568

